In [28]:
import pandas as pd
import re
from textblob import TextBlob
import nltk
from sklearn.feature_extraction.text import CountVectorizer
#from readability import Readability


# Download NLTK data for tokenization
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/paucolomercoll/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /Users/paucolomercoll/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/paucolomercoll/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [17]:
df = pd.read_csv('data/News_dataset/initial_features.csv')

In [18]:
df.head()

,title,text,subject,label,text_length,title_length,length_phrases_no_punctuation_text,length_phrases_no_punctuation_title,qtt_numbers,qtt_noms_propis,qtt_punt,stopwords,emotional,repeated,capital_title,reference_count,word_length
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,True,4659,64,17.904762,3.666667,17,88,113,307,0,0,4,3,4.914921
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,True,4077,64,17.081081,3.333333,9,71,77,253,0,2,4,2,5.237500
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,True,2789,60,20.909091,2.750000,2,75,47,202,0,1,7,2,4.847639
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,True,2461,59,18.000000,9.000000,3,75,51,156,1,0,8,2,5.197943
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,True,5204,69,14.982759,11.000000,34,92,128,353,0,3,4,4,4.752554

### Sentiment Polarity Score

In [19]:
def sentiment_polarity(text):
    return TextBlob(text).sentiment.polarity

df['sentiment_polarity'] = df['text'].apply(sentiment_polarity)

### Subjectivity Score

In [20]:
def subjectivity_score(text):
    return TextBlob(text).sentiment.subjectivity

df['subjectivity_score'] = df['text'].apply(subjectivity_score)

In [25]:
df.head()

,title,text,subject,label,text_length,title_length,length_phrases_no_punctuation_text,length_phrases_no_punctuation_title,qtt_numbers,qtt_noms_propis,qtt_punt,stopwords,emotional,repeated,capital_title,reference_count,word_length,sentiment_polarity,subjectivity_score
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,True,4659,64,17.904762,3.666667,17,88,113,307,0,0,4,3,4.914921,0.037083,0.410250
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,True,4077,64,17.081081,3.333333,9,71,77,253,0,2,4,2,5.237500,0.055880,0.298557
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,True,2789,60,20.909091,2.750000,2,75,47,202,0,1,7,2,4.847639,0.115930,0.316798
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,True,2461,59,18.000000,9.000000,3,75,51,156,1,0,8,2,5.197943,0.035968,0.306569
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,True,5204,69,14.982759,11.000000,34,92,128,353,0,3,4,4,4.752554,0.030093,0.399891

### Average Sentence Length

In [29]:
def avg_sentence_length(text):
    sentences = nltk.sent_tokenize(text)
    if len(sentences) == 0:
        return 0
    return sum(len(nltk.word_tokenize(sentence)) for sentence in sentences) / len(sentences)

df['avg_sentence_length'] = df['text'].apply(avg_sentence_length)

### Character Count

In [30]:
df['character_count'] = df['text'].apply(len)

### Exclamation Mark Count

In [31]:
df['exclamation_mark_count'] = df['text'].apply(lambda x: x.count('!'))

### Question Mark Count

In [32]:
df['question_mark_count'] = df['text'].apply(lambda x: x.count('?'))

### Capitalized Word Count

In [39]:
def capitalized_word_count(text):
    return sum(1 for word in nltk.word_tokenize(text) if word.isupper())

df['capitalized_word_count'] = df['text'].apply(capitalized_word_count)

df.head()

,title,text,subject,label,text_length,title_length,length_phrases_no_punctuation_text,length_phrases_no_punctuation_title,qtt_numbers,qtt_noms_propis,...,capital_title,reference_count,word_length,sentiment_polarity,subjectivity_score,avg_sentence_length,character_count,exclamation_mark_count,question_mark_count,capitalized_word_count
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,True,4659,64,17.904762,3.666667,17,88,...,4,3,4.914921,0.037083,0.410250,29.500000,4659,0,0,12
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,True,4077,64,17.081081,3.333333,9,71,...,4,2,5.237500,0.055880,0.298557,33.952381,4077,0,0,9
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,True,2789,60,20.909091,2.750000,2,75,...,7,2,4.847639,0.115930,0.316798,30.764706,2789,0,0,9
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,True,2461,59,18.000000,9.000000,3,75,...,8,2,5.197943,0.035968,0.306569,27.312500,2461,0,0,5
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,True,5204,69,14.982759,11.000000,34,92,...,4,4,4.752554,0.030093,0.399891,24.675000,5204,1,1,15

In [40]:
df.to_csv('data/News_dataset/final_features.csv', index = False)